feature : OAuth, form login 분리
so1eeee/SofTodo pull request #12
Opened 2024-05-13 06:41 UTC by jaebinGit

커밋이 한 번에 됐네요.
ㅠ

2024-05-13 06:45 UTC, jaebinGit commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
test code

2024-05-15 06:06 UTC, youngroky approved these changes
good

2024-05-15 06:07 UTC, so1eeee requested changes
Good

2024-05-15 06:08 UTC, so1eeee approved these changes
Good

2024-05-15 06:08 UTC, youngroky approved these changes
nice

2024-05-15 06:41 UTC, so1eeee commented
why

2024-05-15 06:50 UTC, merged